exclude: 'src/pip/_vendor/'

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  - id: check-builtin-literals
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-toml
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
    exclude: WHEEL
  - id: forbid-new-submodules
  - id: trailing-whitespace
    exclude: .patch

- repo: https://github.com/psf/black
  rev: 21.7b0
  hooks:
  - id: black
    exclude: |
      (?x)
        ^src/pip/_internal/models|
        ^src/pip/_internal/operations|
        ^src/pip/_internal/\w+\.py$|
        # Tests
        ^tests/data|
        ^tests/unit|  # TODO: we need to break this up in smaller chunks
        ^tests/functional/test_b|
        ^tests/functional/test_c|
        ^tests/functional/test_d|
        ^tests/functional/test_f|
        ^tests/functional/test_h|
        ^tests/functional/test_index|
        ^tests/functional/test_install_c|
        ^tests/functional/test_install_[^c]|
        ^tests/functional/test_install.py|
        ^tests/functional/test_l|
        ^tests/functional/test_n|
        ^tests/functional/test_p|
        ^tests/functional/test_r|
        ^tests/functional/test_s|
        ^tests/functional/test_u|
        ^tests/functional/test_v|
        ^tests/functional/test_w|
        # A blank ignore, to avoid merge conflicts later.
        ^$

- repo: https://gitlab.com/pycqa/flake8
  rev: 3.8.4
  hooks:
  - id: flake8
    additional_dependencies: [
        'flake8-bugbear==20.1.4',
        'flake8-logging-format==0.6.0',
    ]
    exclude: tests/data

- repo: https://github.com/PyCQA/isort
  rev: 5.7.0
  hooks:
  - id: isort
    files: \.py$

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910
  hooks:
  - id: mypy
    exclude: tests
    args: ["--pretty", "--show-error-codes"]
    additional_dependencies: [
        'keyring==23.0.1',
        'nox==2021.6.12',
        'types-docutils==0.1.8',
        'types-six==0.1.9',
    ]

- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.7.0
  hooks:
  - id: python-no-log-warn
  - id: python-no-eval
  - id: rst-backticks
    files: .*\.rst$
    types: [file]
    exclude: NEWS.rst  # The errors flagged in NEWS.rst are old.

- repo: local
  hooks:
  - id: news-fragment-filenames
    name: NEWS fragment
    language: fail
    entry: NEWS fragment files must be named *.(process|removal|feature|bugfix|vendor|doc|trivial).rst
    exclude: ^news/(.gitignore|.*\.(process|removal|feature|bugfix|vendor|doc|trivial).rst)
    files: ^news/

- repo: https://github.com/mgedmin/check-manifest
  rev: '0.46'
  hooks:
  - id: check-manifest
    stages: [manual]
