exclude: 'src/pip/_vendor/'

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: check-builtin-literals
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-toml
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
    exclude: WHEEL
  - id: forbid-new-submodules
  - id: trailing-whitespace
    exclude: .patch

- repo: https://github.com/psf/black
  rev: 19.10b0
  hooks:
  - id: black
    exclude: src/pip/_vendor

- repo: https://gitlab.com/pycqa/flake8
  rev: 3.8.3
  hooks:
  - id: flake8
    additional_dependencies: [
        'flake8-bugbear==20.1.4',
        'flake8-logging-format==0.6.0',
    ]
    exclude: tests/data

- repo: https://github.com/timothycrosley/isort
  rev: 5.4.2
  hooks:
  - id: isort
    files: \.py$

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.770
  hooks:
  - id: mypy
    exclude: docs|tests
    args: ["--pretty"]
  - id: mypy
    name: mypy, for Python 2
    exclude: noxfile.py|tools/automation/release|docs|tests
    args: ["--pretty", "-2"]

- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.6.0
  hooks:
  - id: python-no-log-warn
  - id: python-no-eval
  - id: rst-backticks
    # Validate existing ReST files and NEWS fragments.
    files: .*\.rst$|^news/.*
    types: [file]
    # The errors flagged in NEWS.rst are old.
    exclude: NEWS.rst

- repo: https://github.com/mgedmin/check-manifest
  rev: '0.42'
  hooks:
  - id: check-manifest
