exclude: 'src/pip/_vendor/'

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 8fe62d14e0b4d7d845a7022c5c2c3ae41bdd3f26  # frozen: v4.1.0
  hooks:
  - id: check-builtin-literals
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-toml
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
    exclude: WHEEL
  - id: forbid-new-submodules
  - id: trailing-whitespace
    exclude: .patch

- repo: https://github.com/psf/black
  rev: fc0be6eb1e2a96091e6f64009ee5e9081bf8b6c6  # frozen: 22.1.0
  hooks:
  - id: black

- repo: https://github.com/PyCQA/flake8
  rev: cbeb4c9c4137cff1568659fcc48e8b85cddd0c8d  # frozen: 4.0.1
  hooks:
  - id: flake8
    additional_dependencies: [
        'flake8-bugbear==20.1.4',
        'flake8-logging-format==0.6.0',
        'flake8-implicit-str-concat==0.2.0',
    ]
    exclude: tests/data

- repo: https://github.com/PyCQA/isort
  rev: c5e8fa75dda5f764d20f66a215d71c21cfa198e1  # frozen: 5.10.1
  hooks:
  - id: isort
    files: \.py$

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: f6f816c65d285f8a4a15e0e9965b3dd66ecddd79  # frozen: v0.931
  hooks:
  - id: mypy
    exclude: tests/data
    args: ["--pretty", "--show-error-codes"]
    additional_dependencies: [
        'keyring==23.0.1',
        'nox==2021.6.12',
        'pytest==6.2.5',
        'types-docutils==0.1.8',
        'types-setuptools==57.0.2',
        'types-six==0.1.9',
    ]

- repo: https://github.com/pre-commit/pygrep-hooks
  rev: 6f51a66bba59954917140ec2eeeaa4d5e630e6ce  # frozen: v1.9.0
  hooks:
  - id: python-no-log-warn
  - id: python-no-eval
  - id: rst-backticks
    files: .*\.rst$
    types: [file]
    exclude: NEWS.rst  # The errors flagged in NEWS.rst are old.

- repo: local
  hooks:
  - id: news-fragment-filenames
    name: NEWS fragment
    language: fail
    entry: NEWS fragment files must be named *.(process|removal|feature|bugfix|vendor|doc|trivial).rst
    exclude: ^news/(.gitignore|.*\.(process|removal|feature|bugfix|vendor|doc|trivial).rst)
    files: ^news/

- repo: https://github.com/mgedmin/check-manifest
  rev: 'f98aa338b772b37972c0077016e75c23ac7c63e8'  # frozen: 0.47
  hooks:
  - id: check-manifest
    stages: [manual]
