version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  builder: htmldir
  configuration: docs/html/conf.py

python:
  version: 3.8
  install:
    - requirements: docs/requirements.txt
