language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - pypy
before_install:
    - sudo apt-get install subversion bzr mercurial
    - echo -e "[web]\ncacerts = /etc/ssl/certs/ca-certificates.crt" >> ~/.hgrc
    - git config --global user.email "python-virtualenv@googlegroups.com"
    - git config --global user.name "Pip"
install:
  - pip install --upgrade setuptools
  - pip install pytest pytest-xdist git+https://github.com/pypa/virtualenv@develop#egg=virtualenv scripttest>=1.3 mock
script:
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then py.test -v; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION != '3.2' ]]; then py.test -v -n 8; fi"
notifications:
  irc: "irc.freenode.org#pip"
branches:
  only:
    - develop
    - 1.3.X
    - 1.4.X
env:
  - PYTHONHASHSEED=0
