
language: python

install: .travis/install.sh

script: .travis/run.sh

branches:
  only:
    - master
    - develop
    - /^[0-9]+\.[0-9]+\.X$/

notifications:
  irc:
    channels:
      - "irc.freenode.org#pypa-dev"
    use_notice: true
    skip_join: true

env:
  - TOXENV=py26-integration
  - TOXENV=py26-unit
  - TOXENV=py27-integration
  - TOXENV=py27-unit
  - TOXENV=py32-integration
  - TOXENV=py32-unit
  - TOXENV=py33-integration
  - TOXENV=py33-unit
  - TOXENV=py34-integration
  - TOXENV=py34-unit
  - TOXENV=pypy-integration
  - TOXENV=pypy-unit
  - TOXENV=docs
  - TOXENV=pep8
  - TOXENV=py2pep8
