language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - pypy
before_install:
    - sudo add-apt-repository -y ppa:pypy/ppa
    - sudo apt-get update
    - sudo apt-get install subversion bzr mercurial pypy=2.0.2+dfsg-1~ppa1
    - rm -rf ~/virtualenv/pypy
    - virtualenv -p `which pypy` ~/virtualenv/pypy
    - source ~/virtualenv/pypy/bin/activate
    - echo -e "[web]\ncacerts = /etc/ssl/certs/ca-certificates.crt" >> ~/.hgrc
    - git config --global user.email "python-virtualenv@googlegroups.com"
    - git config --global user.name "Pip"
install: pip install pytest git+https://github.com/pypa/virtualenv@develop#egg=virtualenv scripttest>=1.3 mock
script: py.test
notifications:
  irc: "irc.freenode.org#pip"
branches:
  only:
    - develop
    - 1.3.X
    - 1.4.X
env:
  - PIP_USE_MIRRORS=true
