language: python
before_install:
    - sudo add-apt-repository -y ppa:pypy/ppa
    - sudo apt-get update
    - sudo apt-get install subversion bzr mercurial pypy=2.0.2+dfsg-1~ppa1
    - virtualenv -p `which pypy` ~/virtualenv/pypy2.0
    - source ~/virtualenv/pypy2.0/bin/activate
    - echo -e "[web]\ncacerts = /etc/ssl/certs/ca-certificates.crt" >> ~/.hgrc
    - git config --global user.email "python-virtualenv@googlegroups.com"
    - git config --global user.name "Pip"
#install: pip install pytest git+https://github.com/pypa/virtualenv@develop#egg=virtualenv scripttest>=1.3 mock
install: pip install tox
script: tox
notifications:
  irc: "irc.freenode.org#pip"
branches:
  only:
    - develop
    - 1.3.X
    - 1.4.X
env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py32
  - TOXENV=py33
  - TOXENV=pypy
