environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python33"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python33-x64"
    - PYTHON: "C:\\Python34-x64"
    - PYTHON: "C:\\Python35-x64"

install:
    cmd: "%PYTHON%\\python.exe -m pip install tox"
build: off
test_script:
    # Run for 300 seconds max
    - ps: |
        $p = Start-Process "cmd.exe" '/c %PYTHON%\\Scripts\\tox.exe -e py -- -m unit -n 8' -PassThru
        Wait-Process -id $p.ID -timeout 300

        # Kill the process if it didn't exit after a Wait-Process
        if(!$p.hasExited) {
            echo "Killing the process"
            taskkill /T /F /PID $p.ID
        }
