environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python33"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python33-x64"
    - PYTHON: "C:\\Python34-x64"
    - PYTHON: "C:\\Python35-x64"

install:
    - "%PYTHON%\\python.exe -m pip install tox wheel"
build: off
test_script:
    - "%PYTHON%\\Scripts\\tox.exe -e py -- -m unit -n 8"

after_test:
    # This creates archives in dist/
    - "%PYTHON%\\python.exe setup.py sdist bdist_wheel"
artifacts:
    - path: dist\*
